"""descrizione della migrazione

Revision ID: 0f606e2662c7
Revises: 
Create Date: 2024-12-09 10:51:40.846914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f606e2662c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('developers',
    sa.Column('developer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('developer_id')
    )
    op.create_index(op.f('ix_developers_name'), 'developers', ['name'], unique=False)
    op.create_table('games',
    sa.Column('app_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('estimated_owners', sa.String(length=50), nullable=True),
    sa.Column('peak_ccu', sa.Integer(), nullable=True),
    sa.Column('required_age', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('dlc_count', sa.Integer(), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('reviews', sa.Text(), nullable=True),
    sa.Column('header_image', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('support_url', sa.String(length=500), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('support_windows', sa.Boolean(), nullable=True),
    sa.Column('support_mac', sa.Boolean(), nullable=True),
    sa.Column('support_linux', sa.Boolean(), nullable=True),
    sa.Column('metacritic_score', sa.Integer(), nullable=True),
    sa.Column('metacritic_url', sa.String(length=500), nullable=True),
    sa.Column('user_score', sa.Integer(), nullable=True),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('score_rank', sa.String(length=50), nullable=True),
    sa.Column('achievements', sa.Integer(), nullable=True),
    sa.Column('recommendations', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('average_playtime', sa.Integer(), nullable=True),
    sa.Column('average_playtime_2weeks', sa.Integer(), nullable=True),
    sa.Column('median_playtime', sa.Integer(), nullable=True),
    sa.Column('median_playtime_2weeks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=False)
    op.create_table('languages',
    sa.Column('language_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('language_id')
    )
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.create_table('publishers',
    sa.Column('publisher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('publisher_id')
    )
    op.create_index(op.f('ix_publishers_name'), 'publishers', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('game_categories',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('app_id', 'category_id')
    )
    op.create_index('idx_game_genre', 'game_categories', ['app_id', 'category_id'], unique=False)
    op.create_table('game_developers',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.developer_id'], ),
    sa.PrimaryKeyConstraint('app_id', 'developer_id')
    )
    op.create_index('idx_game_developer', 'game_developers', ['app_id', 'developer_id'], unique=False)
    op.create_table('game_full_audio_languages',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.language_id'], ),
    sa.PrimaryKeyConstraint('app_id', 'language_id')
    )
    op.create_index('idx_game_full_audio_language', 'game_full_audio_languages', ['app_id', 'language_id'], unique=False)
    op.create_table('game_genres',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], ),
    sa.PrimaryKeyConstraint('app_id', 'genre_id')
    )
    op.create_index('idx_game_genre', 'game_genres', ['app_id', 'genre_id'], unique=False)
    op.create_table('game_publishers',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], ),
    sa.PrimaryKeyConstraint('app_id', 'publisher_id')
    )
    op.create_index('idx_game_publisher', 'game_publishers', ['app_id', 'publisher_id'], unique=False)
    op.create_table('game_supported_languages',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.language_id'], ),
    sa.PrimaryKeyConstraint('app_id', 'language_id')
    )
    op.create_index('idx_game_supported_language', 'game_supported_languages', ['app_id', 'language_id'], unique=False)
    op.create_table('game_tags',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('app_id', 'tag_id')
    )
    op.create_index('idx_game_tag', 'game_tags', ['app_id', 'tag_id'], unique=False)
    op.create_table('movies',
    sa.Column('movie_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('packages',
    sa.Column('package_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.PrimaryKeyConstraint('package_id')
    )
    op.create_index(op.f('ix_packages_title'), 'packages', ['title'], unique=False)
    op.create_table('screenshots',
    sa.Column('screenshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ),
    sa.PrimaryKeyConstraint('screenshot_id')
    )
    op.create_table('subpackages',
    sa.Column('subpackage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.package_id'], ),
    sa.PrimaryKeyConstraint('subpackage_id')
    )
    op.create_index(op.f('ix_subpackages_title'), 'subpackages', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subpackages_title'), table_name='subpackages')
    op.drop_table('subpackages')
    op.drop_table('screenshots')
    op.drop_index(op.f('ix_packages_title'), table_name='packages')
    op.drop_table('packages')
    op.drop_table('movies')
    op.drop_index('idx_game_tag', table_name='game_tags')
    op.drop_table('game_tags')
    op.drop_index('idx_game_supported_language', table_name='game_supported_languages')
    op.drop_table('game_supported_languages')
    op.drop_index('idx_game_publisher', table_name='game_publishers')
    op.drop_table('game_publishers')
    op.drop_index('idx_game_genre', table_name='game_genres')
    op.drop_table('game_genres')
    op.drop_index('idx_game_full_audio_language', table_name='game_full_audio_languages')
    op.drop_table('game_full_audio_languages')
    op.drop_index('idx_game_developer', table_name='game_developers')
    op.drop_table('game_developers')
    op.drop_index('idx_game_genre', table_name='game_categories')
    op.drop_table('game_categories')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_publishers_name'), table_name='publishers')
    op.drop_table('publishers')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_developers_name'), table_name='developers')
    op.drop_table('developers')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
