"""new mig

Revision ID: 164a476d375d
Revises: 865c27c66fd5
Create Date: 2024-12-07 13:34:17.418884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164a476d375d'
down_revision: Union[str, None] = '865c27c66fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_tags', sa.Column('tag_value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_tags', 'tag_value')
    # ### end Alembic commands ###
