"""descrizione della migrazione

Revision ID: 43aa2c9908e1
Revises: 0f606e2662c7
Create Date: 2024-12-10 13:02:26.555158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43aa2c9908e1'
down_revision: Union[str, None] = '0f606e2662c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_game_category_app_id', 'game_categories', ['app_id'], unique=False)
    op.create_index('idx_game_category_category_id', 'game_categories', ['category_id'], unique=False)
    op.create_index('idx_game_developer_app_id', 'game_developers', ['app_id'], unique=False)
    op.create_index('idx_game_developer_developer_id', 'game_developers', ['developer_id'], unique=False)
    op.create_index('idx_game_genre_app_id', 'game_genres', ['app_id'], unique=False)
    op.create_index('idx_game_genre_genre_id', 'game_genres', ['genre_id'], unique=False)
    op.create_index('idx_game_publisher_app_id', 'game_publishers', ['app_id'], unique=False)
    op.create_index('idx_game_publisher_publisher_id', 'game_publishers', ['publisher_id'], unique=False)
    op.create_index('idx_game_tag_app_id', 'game_tags', ['app_id'], unique=False)
    op.create_index('idx_game_tag_tag_id', 'game_tags', ['tag_id'], unique=False)
    op.create_index('idx_game_positive_negative', 'games', ['positive', 'negative'], unique=False)
    op.create_index('idx_game_price', 'games', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_game_price', table_name='games')
    op.drop_index('idx_game_positive_negative', table_name='games')
    op.drop_index('idx_game_tag_tag_id', table_name='game_tags')
    op.drop_index('idx_game_tag_app_id', table_name='game_tags')
    op.drop_index('idx_game_publisher_publisher_id', table_name='game_publishers')
    op.drop_index('idx_game_publisher_app_id', table_name='game_publishers')
    op.drop_index('idx_game_genre_genre_id', table_name='game_genres')
    op.drop_index('idx_game_genre_app_id', table_name='game_genres')
    op.drop_index('idx_game_developer_developer_id', table_name='game_developers')
    op.drop_index('idx_game_developer_app_id', table_name='game_developers')
    op.drop_index('idx_game_category_category_id', table_name='game_categories')
    op.drop_index('idx_game_category_app_id', table_name='game_categories')
    # ### end Alembic commands ###
