"""new migdd

Revision ID: b87199d042ab
Revises: 164a476d375d
Create Date: 2024-12-07 15:39:50.619313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87199d042ab'
down_revision: Union[str, None] = '164a476d375d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_developers_name'), 'developers', ['name'], unique=False)
    op.create_index('idx_game_developer', 'game_developers', ['app_id', 'developer_id'], unique=False)
    op.create_index('idx_game_full_audio_language', 'game_full_audio_languages', ['app_id', 'language_id'], unique=False)
    op.create_index('idx_game_genre', 'game_genres', ['app_id', 'genre_id'], unique=False)
    op.create_index('idx_game_publisher', 'game_publishers', ['app_id', 'publisher_id'], unique=False)
    op.create_index('idx_game_supported_language', 'game_supported_languages', ['app_id', 'language_id'], unique=False)
    op.create_index('idx_game_tag', 'game_tags', ['app_id', 'tag_id'], unique=False)
    op.create_index('idx_game_name', 'games', ['name'], unique=False)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=False)
    op.drop_index('name', table_name='languages')
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.create_index(op.f('ix_packages_title'), 'packages', ['title'], unique=False)
    op.create_index(op.f('ix_publishers_name'), 'publishers', ['name'], unique=False)
    op.create_index(op.f('ix_subpackages_title'), 'subpackages', ['title'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_subpackages_title'), table_name='subpackages')
    op.drop_index(op.f('ix_publishers_name'), table_name='publishers')
    op.drop_index(op.f('ix_packages_title'), table_name='packages')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.create_index('name', 'languages', ['name'], unique=True)
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index('idx_game_name', table_name='games')
    op.drop_index('idx_game_tag', table_name='game_tags')
    op.drop_index('idx_game_supported_language', table_name='game_supported_languages')
    op.drop_index('idx_game_publisher', table_name='game_publishers')
    op.drop_index('idx_game_genre', table_name='game_genres')
    op.drop_index('idx_game_full_audio_language', table_name='game_full_audio_languages')
    op.drop_index('idx_game_developer', table_name='game_developers')
    op.drop_index(op.f('ix_developers_name'), table_name='developers')
    # ### end Alembic commands ###
